name: Sigma Deployment

on:
  workflow_dispatch:
    inputs:
      customer:
        description: Customer Name
        required: true

      vendor:
        description: Vendor Name
        required: true

jobs:

  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validation Stage
        run: |
          echo "Validation Started"
          sleep 10
          echo "Validation Success"

  build:
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: |
          echo "Build Started"
          sleep 10
          echo "Build Success"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test Stage
        run: |
          echo "Test Started"
          sleep 10
          echo "Test Success"

  deployment:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Stage
        run: |
          echo "Deployment Started"
          sleep 15
          echo "Deployment Success"

      - name: Generate Artifact
        run: |
          mkdir artifact
          echo '{
            "deployment_id":"GH123",
            "rules_deployed":20,
            "failed_rules":0
          }' > artifact/result.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-result
          path: artifact/result.json
